package gestion.almacenes.forms.registrarSalida;

import gestion.almacenes.dao.entities.Insumo;
import gestion.almacenes.controller.InsumoControllerImpl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import gestion.almacenes.controller.IInsumoController;
import gestion.almacenes.controller.IInsumoSaleController;
import gestion.almacenes.controller.InsumoSaleControllerImpl;
import gestion.almacenes.dao.entities.InsumoSale;
import java.util.UUID;

/**
 *
 * @author Bacilio
 */
public class RegistrarSalida extends javax.swing.JInternalFrame {

    private final IInsumoController iInsumoService;
    private final IInsumoSaleController iInsumoSaleController;

    /**
     * Creates new form GestionUsuario
     */
    public RegistrarSalida() {
        initComponents();
        this.iInsumoService = new InsumoControllerImpl();
        this.iInsumoSaleController = new InsumoSaleControllerImpl();
        btnRegistrar.setEnabled(true);
        cargarComboInsumos();
        cargarListaInsumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        txtStockInicial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboInsumos = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtStockFinal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCantSale = new javax.swing.JTextField();
        panelActions = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInsumos = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Entrada de Insumo");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 550));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setName("formGestionUsuario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 550));

        panelDatos.setBackground(java.awt.SystemColor.inactiveCaption);
        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtStockInicial.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtStockInicial.setForeground(new java.awt.Color(0, 0, 204));
        txtStockInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Stock Inicial:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Insumos:");

        comboInsumos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        comboInsumos.setForeground(new java.awt.Color(0, 0, 204));
        comboInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInsumosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Stock Final:");

        txtStockFinal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtStockFinal.setForeground(new java.awt.Color(0, 0, 204));
        txtStockFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad Saliente:");

        txtCantSale.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtCantSale.setForeground(new java.awt.Color(0, 0, 204));
        txtCantSale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantSale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantSaleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(16, 16, 16)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantSale))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(61, 61, 61))
                            .addComponent(txtStockFinal)))
                    .addComponent(comboInsumos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantSale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelActions.setBackground(java.awt.SystemColor.inactiveCaption);
        panelActions.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegistrar.setBackground(new java.awt.Color(153, 255, 102));
        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.setName("btnRegistrar"); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(153, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.setName("btnRegistrar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActionsLayout = new javax.swing.GroupLayout(panelActions);
        panelActions.setLayout(panelActionsLayout);
        panelActionsLayout.setHorizontalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelActionsLayout.setVerticalGroup(
            panelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActionsLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        panelLista.setBackground(java.awt.SystemColor.inactiveCaption);
        panelLista.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbInsumos.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tbInsumos);

        javax.swing.GroupLayout panelListaLayout = new javax.swing.GroupLayout(panelLista);
        panelLista.setLayout(panelListaLayout);
        panelListaLayout.setHorizontalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelListaLayout.setVerticalGroup(
            panelListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String idInsumo = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getId();
        String proveddorId = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getIdProveedor();
        String serie = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getSerie();
        String tipo = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getTipo();
        String nombre = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getNombre();
        double precio = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getPrecio();
        String uumm = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getUnidad();

        Insumo insumo = new Insumo();
        insumo.setId(idInsumo);
        insumo.setIdProveedor(proveddorId);
        insumo.setPrecio(precio);
        insumo.setNombre(nombre);
        insumo.setSerie(serie);
        insumo.setTipo(tipo);
        insumo.setUnidad(uumm);
        insumo.setStockFinal(Integer.parseInt(txtStockFinal.getText()));
        insumo.setStockInicial(Integer.parseInt(txtStockFinal.getText()));

        InsumoSale entra = new InsumoSale();
        entra.setCantidad(Integer.parseInt(txtCantSale.getText()));
        entra.setId(UUID.randomUUID().toString());
        entra.setInsumoId(idInsumo);

        String saliente = iInsumoSaleController.insumoSaleCreate(entra);
 
        String message = iInsumoService.insumoUpdate(insumo);
        JOptionPane.showMessageDialog(null, message + "\n" + saliente, "Salida de Insumo registrado", HEIGHT);
        limpiarInsumo();
        cargarListaInsumo();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarInsumo();
        btnRegistrar.setEnabled(true);
        //cargarComboInsumos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInsumosActionPerformed
        // TODO add your handling code here:
        String insumoId = comboInsumos.getItemAt(comboInsumos.getSelectedIndex()).getId();

        Insumo insumo = iInsumoService.insumoGet(insumoId);
        if (insumo == null) {
            JOptionPane.showMessageDialog(null, "Insumo no encontrado", "Buscar Insumo", HEIGHT);

        } else {
            txtStockInicial.setText(String.valueOf(insumo.getStockInicial()));
        }
    }//GEN-LAST:event_comboInsumosActionPerformed

    private void txtCantSaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantSaleKeyReleased
        // TODO add your handling code here:
        int cantidad = Integer.parseInt(txtCantSale.getText());
        int suma = Integer.parseInt(txtStockInicial.getText()) - cantidad;
        txtStockFinal.setText(String.valueOf(suma));
    }//GEN-LAST:event_txtCantSaleKeyReleased

    private void limpiarInsumo() {
        txtCantSale.setText("");
        txtStockFinal.setText("");
        btnRegistrar.setEnabled(true);
    }

    private void cargarListaInsumo() {
        List<Insumo> listaInsumo = this.iInsumoService.insumoRead();
        DefaultTableModel tableInsumo = new DefaultTableModel();
        tableInsumo.addColumn("ID");
        tableInsumo.addColumn("PROVEEDOR");
        tableInsumo.addColumn("NOMBRE");
        tableInsumo.addColumn("PRECIO");
        tableInsumo.addColumn("SERIE");
        tableInsumo.addColumn("TIPO");
        tableInsumo.addColumn("S-I");
        tableInsumo.addColumn("UUMM");
        tableInsumo.addColumn("S-F");

        for (int i = 0; i < listaInsumo.size(); i++) {
            tableInsumo.addRow(new Object[]{
                listaInsumo.get(i).getId(),
                listaInsumo.get(i).getIdProveedor(),
                listaInsumo.get(i).getNombre(),
                listaInsumo.get(i).getPrecio(),
                listaInsumo.get(i).getSerie(),
                listaInsumo.get(i).getTipo(),
                listaInsumo.get(i).getStockInicial(),
                listaInsumo.get(i).getUnidad(),
                listaInsumo.get(i).getStockFinal(),});
        }

        tbInsumos.setModel(tableInsumo);
    }

    private void cargarComboInsumos() {
        comboInsumos.removeAllItems();
        List<Insumo> insumos = iInsumoService.insumoRead();
        for (int i = 0; i < insumos.size(); i++) {
            comboInsumos.addItem(insumos.get(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Insumo> comboInsumos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelActions;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelLista;
    private javax.swing.JTable tbInsumos;
    private javax.swing.JTextField txtCantSale;
    private javax.swing.JTextField txtStockFinal;
    private javax.swing.JTextField txtStockInicial;
    // End of variables declaration//GEN-END:variables
}
