/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.almacenes.forms;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bacilio
 */
public class Principal extends javax.swing.JFrame {

    GestionUsuario gestionUsuario = new GestionUsuario();
    GestionInsumo gestionInsumo = new GestionInsumo();
    GestionProveedor gestionProveedor = new GestionProveedor();
    GestionReporte gestionReporte = new GestionReporte();
    RegistrarEntrada registrarEntrada = new RegistrarEntrada();
    RegistrarSalida registrarSalida = new RegistrarSalida();
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        almacen = new javax.swing.JMenu();
        regEntra = new javax.swing.JMenuItem();
        regSalida = new javax.swing.JMenuItem();
        gestionar = new javax.swing.JMenu();
        gestInsumo = new javax.swing.JMenuItem();
        gestUsuario = new javax.swing.JMenuItem();
        gestProveedor = new javax.swing.JMenuItem();
        gestReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setPreferredSize(new java.awt.Dimension(1100, 850));

        escritorio.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion/almacenes/forms/Ag7H.gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("BIENVENIDOS AL ALMACÉN...!!!");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        almacen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        almacen.setText("ALMACÉN");

        regEntra.setText("REGISTRAR ENTRADA");
        regEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEntraActionPerformed(evt);
            }
        });
        almacen.add(regEntra);

        regSalida.setText("REGISTRAR SALIDA");
        regSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regSalidaActionPerformed(evt);
            }
        });
        almacen.add(regSalida);

        menu.add(almacen);

        gestionar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gestionar.setText("GESTIONAR");

        gestInsumo.setText("GESTIONAR INSUMO");
        gestInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestInsumoActionPerformed(evt);
            }
        });
        gestionar.add(gestInsumo);

        gestUsuario.setText("GESTIONAR USUARIO");
        gestUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestUsuarioActionPerformed(evt);
            }
        });
        gestionar.add(gestUsuario);

        gestProveedor.setText("GESTIONAR PROVEEDOR");
        gestProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestProveedorActionPerformed(evt);
            }
        });
        gestionar.add(gestProveedor);

        gestReporte.setText("GESTIONAR REPORTE");
        gestReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestReporteActionPerformed(evt);
            }
        });
        gestionar.add(gestReporte);

        menu.add(gestionar);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEntraActionPerformed
        if (!registrarEntrada.isShowing()) {

            try {
                escritorio.add(registrarEntrada);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = registrarEntrada.getSize();
                registrarEntrada.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                registrarEntrada.show();
                registrarEntrada.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_regEntraActionPerformed

    private void regSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regSalidaActionPerformed
        if (!registrarSalida.isShowing()) {

            try {
                escritorio.add(registrarSalida);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = registrarSalida.getSize();
                registrarSalida.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                registrarSalida.show();
                registrarSalida.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_regSalidaActionPerformed

    private void gestUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestUsuarioActionPerformed
        if (!gestionUsuario.isShowing()) {

            try {
                escritorio.add(gestionUsuario);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = gestionUsuario.getSize();
                gestionUsuario.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                gestionUsuario.show();
                gestionUsuario.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_gestUsuarioActionPerformed

    private void gestInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestInsumoActionPerformed
        if (!gestionInsumo.isShowing()) {

            try {
                escritorio.add(gestionInsumo);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = gestionInsumo.getSize();
                gestionInsumo.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                gestionInsumo.show();
                gestionInsumo.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_gestInsumoActionPerformed

    private void gestProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestProveedorActionPerformed
        if (!gestionProveedor.isShowing()) {

            try {
                escritorio.add(gestionProveedor);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = gestionProveedor.getSize();
                gestionProveedor.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                gestionProveedor.show();
                gestionProveedor.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_gestProveedorActionPerformed

    private void gestReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestReporteActionPerformed
        if (!gestionReporte.isShowing()) {

            try {
                escritorio.add(gestionReporte);
                Dimension panelDimension = escritorio.getSize();
                Dimension registroDimension = gestionReporte.getSize();
                gestionReporte.setLocation((panelDimension.width - registroDimension.width) / 2, (panelDimension.height - registroDimension.height) / 2);
                gestionReporte.show();
                gestionReporte.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "bien");
        }
    }//GEN-LAST:event_gestReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(almacenl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu almacen;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem gestInsumo;
    private javax.swing.JMenuItem gestProveedor;
    private javax.swing.JMenuItem gestReporte;
    private javax.swing.JMenuItem gestUsuario;
    private javax.swing.JMenu gestionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem regEntra;
    private javax.swing.JMenuItem regSalida;
    // End of variables declaration//GEN-END:variables
}
